config/routes.rb
Rails.application.routes.draw do

  resources :saved_searches do
    collection do
      get 'query_model'
      get 'query_model_by_form'
      post 'query_model_by_form'
      get 'render_table'
    end
  end

end

app/models/saved_search.rb
class SavedSearch < ActiveRecord::Base

  before_save :set_available_fields
  serialize :available_fields
  serialize :query_parameters
  serialize :display_fields

  def set_available_fields
    attributes = Array.new
    for attribute in eval(self.model_name).columns
      attributes << attribute.name
    end
    self.available_fields = attributes
    validate_fields
  end

  # Perform the query that is specified in the query_parameters attribute
  def execute_query
    query_parameters = self.query_parameters
    query_parameters.delete(:redirect_controller)
    query_parameters.delete(:redirect_action)
    query_parameters.delete(:saved_search_id)
    #sql = "#{query_parameters}"
    sql = String.new
    query_parameters.each do |key,val|
      if val.class == TrueClass || val.class == FalseClass
        sql << "#{key} == #{val} and "
      else
        sql << "#{key} like '#{val}' and "
      end
    end
    sql = sql.slice(0, sql.length-4)
    self.last_query = sql
    self.save
    eval(self.model_name).where(sql)
  end

  # This method translates the inputs from the form into the correct
  # datatypes for the search model.  For instance, "0" is returned
  # by the form, but it should be "false" in the search model.
  def validate_fields
    for key in self.query_parameters.keys
      for column in eval("#{self.model_name}").columns
        if key == column.name.to_sym
          if column.type == :boolean
            if self.query_parameters[key] == "0"
              self.query_parameters[key] = false
            else
              self.query_parameters[key] = true
            end
          end
        end
      end
    end
  end



end

app/controllers/saved_searches/application_controller.rb
module SavedSearches
  class ApplicationController < ActionController::Base
  end
end

app/controllers/saved_searches_controller.rb
class SavedSearchesController < ApplicationController
  layout 'single_column'

  # GET /saved_searches
  # GET /saved_searches.xml
  def index
    @saved_searches = SavedSearch.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @saved_searches }
    end
  end

  # GET /saved_searches/1
  # GET /saved_searches/1.xml
  def show
    @saved_search = SavedSearch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @saved_search }
    end
  end

  # GET /saved_searches/new
  # GET /saved_searches/new.xml
  def new
    @saved_search = SavedSearch.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @saved_search }
    end
  end

  # GET /saved_searches/1/edit
  def edit
    @saved_search = SavedSearch.find(params[:id])
  end

  # POST /saved_searches
  # POST /saved_searches.xml
  def create
    @saved_search = SavedSearch.new(params[:saved_search])

    respond_to do |format|
      if @saved_search.save
        format.html { redirect_to(@saved_search, :notice => 'Saved search was successfully created.') }
        format.xml  { render :xml => @saved_search, :status => :created, :location => @saved_search }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @saved_search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /saved_searches/1
  # PUT /saved_searches/1.xml
  def update
    @saved_search = SavedSearch.find(params[:id])

    respond_to do |format|
      if @saved_search.update_attributes(params[:saved_search])
        format.html { redirect_to(@saved_search, :notice => 'Saved search was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @saved_search.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /saved_searches/1
  # DELETE /saved_searches/1.xml
  def destroy
    @saved_search = SavedSearch.find(params[:id])
    @saved_search.destroy

    respond_to do |format|
      format.html { redirect_to(saved_searches_url) }
      format.xml  { head :ok }
    end
  end

  def query_model
    @saved_search = SavedSearch.find(params[:id])
    @model_name = eval(@saved_search.model_name).new
  end

  def query_model_by_form
    @original_ss = SavedSearch.find(params[params[:model_name]][:saved_search_id])
    persist_key = "#{params[:model_name].underscore.pluralize}_user" 
    persist_value = current_user.id
    SavedSearch.connection.delete("delete from saved_searches where persist_key = '#{persist_key}' and persist_value = #{persist_value}")

    @saved_search = SavedSearch.new
    @saved_search.persist = true
    @saved_search.model_name = params[:model_name]
    @saved_search.query_parameters = Hash.new
    @saved_search.persist_key = "#{params[:model_name].underscore.pluralize}_user"
    @saved_search.persist_value = current_user
    for field in params[@saved_search.model_name].keys
      if params[@saved_search.model_name][field.to_sym] != ""
        @saved_search.query_parameters.merge!({field.to_sym => params[@saved_search.model_name][field.to_sym]})
      end
    end
    @saved_search.display_fields = @original_ss.display_fields
    @saved_search.save
    redirect_to :controller => params[@saved_search.model_name][:redirect_controller],
                :action => params[@saved_search.model_name][:redirect_action]
  end

  def render_table
    @saved_search = SavedSearch.find(params[:id])
  end

end

app/helpers/saved_searches/application_helper.rb
module SavedSearches
  module ApplicationHelper
 def render_table(id)
     saved_search = SavedSearch.find(id)
     if saved_search.display_fields.nil?
       fields = saved_search.available_fields
     else
       fields = saved_search.display_fields
     end
     str = "<table class='tablesorter'>"
     str << "<thead>"
     str << "<tr>"
     for header in fields
       str << "<th>#{header[:label]}</th>"
     end
     str << "<tr>"
     str << "</thead>"
     str << "<tbody>"
     for data in saved_search.execute_query
       str << "<tr>"
       for field in fields
         if field.class == Hash
           text = eval("data.#{field[:name]}")
         else
           text = eval("data.#{field}")
         end
         str << "<td>#{text}</td>"
       end
       str << "<td><a href='/#{saved_search.model_name.underscore.pluralize}/#{eval("data.id")}/edit'>Edit</a></td>"
       str << "</tr>"
     end
     str << "</tbody>"
     str << "</table>"
     str << "<p>Using Saved Search: #{saved_search.id}</p>"
     str.html_safe
   end
  end
end

app/helpers/saved_searches/saved_searches_helper.rb
module SavedSearches 
  module SavedSearchesHelper
 def render_table(id)
     saved_search = SavedSearch.find(id)
     if saved_search.display_fields.nil?
       fields = saved_search.available_fields
     else
       fields = saved_search.display_fields
     end
     str = "<table class='tablesorter'>"
     str << "<thead>"
     str << "<tr>"
     for header in fields
       str << "<th>#{header[:label]}</th>"
     end
     str << "<tr>"
     str << "</thead>"
     str << "<tbody>"
     for data in saved_search.execute_query
       str << "<tr>"
       for field in fields
         if field.class == Hash
           text = eval("data.#{field[:name]}")
         else
           text = eval("data.#{field}")
         end
         str << "<td>#{text}</td>"
       end
       str << "<td><a href='/#{saved_search.model_name.underscore.pluralize}/#{eval("data.id")}/edit'>Edit</a></td>"
       str << "</tr>"
     end
     str << "</tbody>"
     str << "</table>"
     str << "<p>Using Saved Search: #{saved_search.id}</p>"
     str.html_safe
   end
  end
end

app/views/layouts/saved_searches/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SavedSearches</title>
  <%= stylesheet_link_tag    "saved_searches/application", :media => "all" %>
  <%= javascript_include_tag "saved_searches/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/saved_searches/_form.html.erb
<%= form_for(@saved_search) do |f| %>
  <% if @saved_search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saved_search.errors.count, "error") %> prohibited this saved_search from being saved:</h2>

      <ul>
      <% @saved_search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model_name %><br />
    <%= f.text_field :model_name %>
  </div>
  <div class="field">
    <%= f.label :available_fields %><br />
    <%= f.text_area :available_fields %>
  </div>
  <div class="field">
    <%= f.label :query_parameters %><br />
    <%= f.text_area :query_parameters %>
  </div>
  <div class="field">
    <%= f.label :persist %><br />
    <%= f.check_box :persist %>
  </div>
  <div class="field">
    <%= f.label :persist_key %><br />
    <%= f.text_area :persist_key %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saved_searches/_query_model.html.erb
<%= semantic_form_for @saved_search.model_name,
                      :url => query_model_by_form_saved_searches_path(:model_name=> @saved_search.model_name) do |f| %>
    <%= f.inputs do %>
        <% for field in @saved_search.display_fields %>
          <% if field[:type] == "boolean" %>
            <%= f.input field[:name].to_sym, :as=>:boolean, :label=>field[:label] %>
          <% else %>
            <%= f.input field[:name].to_sym, :label=>field[:label] %>
          <% end %>
        <% end %>
        <%= f.input :redirect_controller, :as=>:hidden, :value=>params[:controller] %>
        <%= f.input :redirect_action, :as=>:hidden, :value => params[:action] %>
        <%= f.input :saved_search_id, :as=>:hidden, :value => @saved_search.id %>
        <%= f.actions do %>
              <%= f.action :submit, :as => :button %>
       <% end %>
    <% end %>
<% end %>

app/views/saved_searches/_render_table.html.erb
<%= render_table(@saved_search) %>

app/views/saved_searches/edit.html.erb
<h1>Editing saved_search</h1>

<%= render 'form' %>

<%= link_to 'Show', @saved_search %> |
<%= link_to 'Back', saved_searches_path %>

app/views/saved_searches/index.html.erb
<h1>Saved Searches</h1>

<table class='tablesorter'>
  <thead>
  <tr>
    <th>Model Name</th>
    <th>Available Fields</th>
    <th>Query Parameters</th>
    <th>Persist</th>
    <th>Persist Key</th>
    <th>Persist Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @saved_searches.each do |saved_search| %>
      <tr>
        <td><%= saved_search.model_name %></td>
        <td><%= saved_search.available_fields %></td>
        <td><%= saved_search.query_parameters %></td>
        <td><%= saved_search.persist %></td>
        <td><%= saved_search.persist_key %></td>
        <td><%= saved_search.persist_value %></td>
        <td><%= link_to 'Show', saved_search %></td>
        <td><%= link_to 'Edit', edit_saved_search_path(saved_search) %></td>
        <td><%= link_to 'Destroy', saved_search, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Saved Search', new_saved_search_path %>

app/views/saved_searches/new.html.erb
<h1>New saved_search</h1>

<%= render 'form' %>

<%= link_to 'Back', saved_searches_path %>

app/views/saved_searches/query_model.html.erb
<%= semantic_form_for @model_name,
                      :url => {:action => "query_model_by_form", :controller => "saved_searches", :model_name => @model_name.class} do |f| %>
    <%= f.inputs do %>
        <% for field in @saved_search.available_fields %>
            <%= f.input field.to_sym %>
        <% end %>
        <%= f.commit_button "Search" %>
    <% end %>
<% end %>

app/views/saved_searches/render_table.html.erb
<%= render :partial=>'render_table' %>

app/views/saved_searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Model name:</b>
  <%= @saved_search.model_name %>
</p>

<p>
  <b>Available fields:</b>
  <%= @saved_search.available_fields %>
</p>

<p>
  <b>Query parameters:</b>
  <%= @saved_search.query_parameters %>
</p>

<p>
  <b>Persist:</b>
  <%= @saved_search.persist %>
</p>

<p>
  <b>Persist key:</b>
  <%= @saved_search.persist_key %>
</p>


<%= link_to 'Edit', edit_saved_search_path(@saved_search) %> |
<%= link_to 'Back', saved_searches_path %>